name: run
on:
  schedule:
    - cron: "0 17 * * 0" # Runs every Sunday at 17:00 (UTC)
    - cron: "10 * * * *"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        default: Matrix-Testing
        options:
          - Matrix
          - Matrix-Testing

jobs:
  run:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
      - run: rye pin 3.12
      - run: rye sync
      - name: run marvin
        env:
          MATRIX_ACCESSTOKEN: ${{ secrets.MATRIX_ACCESSTOKEN }}
          MATRIX_HOMESERVER: ${{ secrets.MATRIX_HOMESERVER }}
          MATRIX_MESSAGE: ${{ secrets.MATRIX_MESSAGE }}
          MATRIX_ROOMID: ${{ secrets.MATRIX_ROOMID }}
        run: rye run marvin
