name: run
on:
  schedule:
    - cron: "0 18 * * 0" # Runs every Sunday at 17:00 (UTC)
  workflow_dispatch:

jobs:
  run:
    environment: Matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
      - run: rye pin 3.12
      - run: rye sync
      - name: run marvin
        env:
          MATRIX_ACCESSTOKEN: ${{ secrets.MATRIX_ACCESSTOKEN }}
          MATRIX_HOMESERVER: ${{ secrets.MATRIX_HOMESERVER }}
          MATRIX_MESSAGE: ${{ secrets.MATRIX_MESSAGE }}
          MATRIX_ROOMID: ${{ secrets.MATRIX_ROOMID }}
        run: rye run marvin
